comment:
  layout: reach
  behavior: new
  require_changes: true
coverage:
  range: 0..100
  round: nearest
  precision: 1
  status:
    patch:
      default:
        target: 50%
        threshold: 10%
    project:
      default:
        target: 50%
        threshold: 10%
      client-app:
        flags:
          - client-app
flags:
  client-app:
    paths:
      - apps/client-app
