name: Nx CI

on:
  push:
    branches:
      - main
      - renovate-github/**
      - test-affected
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  use_github_action:
    name: Testing GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use the package manager cache if available
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: IsAffected
        id: check_affected
        uses: chill-viking/is-nx-affected@v0.0.5
        with:
          project: clien-app
          base: main

      - name: Echo when affected
        if: steps.check_affected.outputs.is-affected == 'true'
        run: |
          echo "hello"

      - name: Echo when not affected
        if: steps.check_affected.outputs.is-affected == 'false'
        run: |
          echo "goodbye"
